#!/usr/bin/expect

set timeout -1
spawn "/serverfiles/bf2142-linuxded-1.10.112.0-installer.sh" --keep --target /serverfiles/bf2142

expect {
       eof { send_user "\nunexpected eof in extraction\n"; exit 1 }
       "*ress return"
}
       
send "^c"

send_user "\nExtraction finished\n"
